In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('dataset/seller_info_dm1_2627.csv')

## Exploratory Data Analysis

In [31]:
df.head(10)

,sp_id,n_listings,price_median,savings_amount_median,daysonmarket_median,mileage_median,year_median,vehicle_age_median,owner_count_median,horsepower_median,...,n_listing_days,listing_span_days,dominant_body_type,dominant_fuel_type,dominant_transmission,dominant_wheel_system,dominant_listing_color,franchise_status,new_used_profile,seller_rating_class
0,404771.0,30,6700.0,431.0,13.0,193193.5,2011.0,9.0,2.0,258.5,...,15,156,suv_crossover,gasoline,a,NaN,gray,independent,used_only,medium
1,336590.0,17,10995.0,505.0,24.0,87589.0,2012.0,7.0,2.0,182.0,...,14,589,suv_crossover,gasoline,a,awd,silver,independent,used_only,medium
2,392016.0,18,7645.0,632.0,43.0,151434.0,2010.5,9.5,2.0,205.0,...,15,97,sedan,gasoline,a,NaN,blue,independent,used_only,low
3,294197.0,12,23449.0,479.0,18.0,31186.0,2017.0,3.0,1.0,178.0,...,7,338,sedan,gasoline,a,NaN,unknown,franchise,used_only,medium
4,372085.0,14,8990.0,505.5,213.0,144471.5,2007.5,12.0,1.5,240.0,...,6,315,suv_crossover,gasoline,a,NaN,silver,independent,used_only,medium
5,67741.0,103,85375.0,1.0,42.0,5528.0,2018.0,2.0,1.0,350.0,...,54,526,suv_crossover,gasoline,a,NaN,unknown,franchise,mixed,medium
6,297713.0,281,29491.0,0.0,26.0,13.0,2020.0,0.0,1.0,252.0,...,100,333,suv_crossover,gasoline,a,NaN,black,franchise,mixed,low
7,346621.0,163,28770.0,0.0,39.0,24.0,2020.0,0.0,1.0,300.0,...,73,784,suv_crossover,gasoline,a,NaN,white,franchise,mixed,high
8,266490.0,54,85898.0,3043.5,16.0,14230.5,2018.0,2.0,1.0,400.0,...,27,1098,suv_crossover,gasoline,a,awd,black,franchise,mixed,medium
9,382081.0,30,9789.5,623.0,28.0,118936.5,2011.0,9.0,2.0,205.0,...,18,454,suv_crossover,gasoline,a,NaN,gray,independent,used_only,low

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13843 entries, 0 to 13842
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sp_id                        13843 non-null  float64
 1   n_listings                   13843 non-null  int64
 2   price_median                 13843 non-null  float64
 3   savings_amount_median        13843 non-null  float64
 4   daysonmarket_median          13843 non-null  float64
 5   mileage_median               13842 non-null  float64
 6   year_median                  13843 non-null  float64
 7   vehicle_age_median           13842 non-null  float64
 8   owner_count_median           13804 non-null  float64
 9   horsepower_median            13837 non-null  float64
 10  engine_displacement_median   10450 non-null  float64
 11  city_fuel_economy_median     13827 non-null  float64
 12  highway_fuel_economy_median  13827 non-null  float64
 13  back_legroom_median          13824 non-null  float64
 14  front_legroom_median         13836 non-null  float64
 15  fuel_tank_volume_median      13836 non-null  float64
 16  height_median                13837 non-null  float64
 17  length_median                13837 non-null  float64
 18  width_median                 13837 non-null  float64
 19  pct_isCab                    13816 non-null  float64
 20  pct_is_new                   13843 non-null  float64
 21  pct_salvage                  13816 non-null  float64
 22  pct_theft_title              13816 non-null  float64
 23  n_listing_days               13843 non-null  int64
 24  listing_span_days            13843 non-null  int64
 25  dominant_body_type           13843 non-null  str
 26  dominant_fuel_type           13843 non-null  str
 27  dominant_transmission        13843 non-null  str
 28  dominant_wheel_system        3325 non-null   str
 29  dominant_listing_color       13843 non-null  str
 30  franchise_status             13843 non-null  str
 31  new_used_profile             13843 non-null  str
 32  seller_rating_class          13843 non-null  str
dtypes: float64(22), int64(3), str(8)
memory usage: 3.5 MB

In [33]:
df[df['vehicle_age_median'].isnull()]

,sp_id,n_listings,price_median,savings_amount_median,daysonmarket_median,mileage_median,year_median,vehicle_age_median,owner_count_median,horsepower_median,...,n_listing_days,listing_span_days,dominant_body_type,dominant_fuel_type,dominant_transmission,dominant_wheel_system,dominant_listing_color,franchise_status,new_used_profile,seller_rating_class
3520,293033.0,7,42180.0,4160.0,298.0,1784.0,2020.0,NaN,NaN,255.0,...,6,57,sedan,gasoline,a,awd,black,franchise,used_only,high

In [34]:
df[df['dominant_body_type'] == 'suv_crossover']['vehicle_age_median'].mean()

np.float64(3.023822869955157)